# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
issue_templates:
  - name: ğŸ§¯ íŠ¸ëŸ¬ë¸”ìŠˆíŒ…
    description: ì´ìŠˆ ë°œìƒ ë‚´ìš©ì„ ì •ë¦¬í•  ë•Œ ì‚¬ìš©í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤.
    file: troubleshooting.md